version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            npm i
            cd src
            npm i
            cd ..
            npm cache clean --force
            rm -rf node_modules package-lock.json
            npm install
            npm run build
            mkdir artifacts

      - store_artifacts:
          path: /artifacts/artifactfiles
   